AWSTemplateFormatVersion: '2010-09-09'
Description: Basic Lambda setup

Resources:

  #Add Cognito Userpool
  CognitoUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: scansource-user-pool

      UsernameAttributes:
        - email

      AutoVerifiedAttributes:
        - email

      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireUppercase: true
          RequireLowercase: true
          RequireNumbers: true
          RequireSymbols: false

  #Cognito App Client
  CognitoUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: scansource-app-client
      UserPoolId: !Ref CognitoUserPool

      GenerateSecret: false

      ExplicitAuthFlows:
        - ALLOW_USER_PASSWORD_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH  

  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      #RoleName: lambda-execution-role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: lambda-logs
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:*
                Resource: "*"

  WeatherLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: weather-lambda
      Runtime: nodejs18.x
      Handler: index.handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Code:
        S3Bucket: scansource-technical-assessment-bucket #S3 Bucket goes here
        S3Key: lambda1.zip 

  CryptoLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: crypto-lambda
      Runtime: python3.11
      Handler: lambda_function.lambda_handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Code:
        S3Bucket: scansource-technical-assessment-bucket #S3 Bucket goes here
        S3Key: lambda2.zip

  ApiGateway:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: scansource-api

  #API Authorizer goes in our ApiGateway Resource
  ApiAuthorizer:
    Type: AWS::ApiGateway::Authorizer
    Properties:
      Name: CognitoAuthorizer
      Type: COGNITO_USER_POOLS
      IdentitySource: method.request.header.Authorization
      RestApiId: !Ref ApiGateway
      ProviderARNs:
        - !GetAtt CognitoUserPool.Arn #Cognito app ARN here

  WeatherResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref ApiGateway
      ParentId: !GetAtt ApiGateway.RootResourceId
      PathPart: weather

  CryptoResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref ApiGateway
      ParentId: !GetAtt ApiGateway.RootResourceId
      PathPart: crypto

  WeatherMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref ApiGateway
      ResourceId: !Ref WeatherResource
      HttpMethod: GET
      #AuthorizationType: NONE
      AuthorizationType: COGNITO_USER_POOLS
      AuthorizerId: !Ref ApiAuthorizer
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${WeatherLambda.Arn}/invocations"

  CryptoMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref ApiGateway
      ResourceId: !Ref CryptoResource
      HttpMethod: GET
      #AuthorizationType: NONE
      AuthorizationType: COGNITO_USER_POOLS
      AuthorizerId: !Ref ApiAuthorizer
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${CryptoLambda.Arn}/invocations"

  WeatherLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref WeatherLambda
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com

  CryptoLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref CryptoLambda
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com

  ApiDeploymentV4:
    Type: AWS::ApiGateway::Deployment
    DependsOn:
      - WeatherMethod
      - CryptoMethod
    Properties:
      RestApiId: !Ref ApiGateway
      StageName: prod


Outputs:

  ApiUrl:
    Description: API Gateway URL
    Value: !Sub "https://${ApiGateway}.execute-api.${AWS::Region}.amazonaws.com/prod"

  UserPoolId:
    Value: !Ref CognitoUserPool

  UserPoolClientId:
    Value: !Ref CognitoUserPoolClient